# Generated by Django 4.2.10 on 2025-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log_page_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_current_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Current Date Time')),
                ('page_python_app', models.CharField(blank=True, max_length=100, null=True)),
                ('page_function_name', models.CharField(blank=True, max_length=500, null=True)),
                ('page_user', models.CharField(blank=True, max_length=100, null=True)),
                ('page_user_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('page_user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('page_user_referer', models.CharField(blank=True, max_length=500, null=True)),
                ('page_user_language', models.CharField(blank=True, max_length=100, null=True)),
                ('page_user_device', models.CharField(blank=True, max_length=100, null=True)),
                ('page_user_os', models.CharField(blank=True, max_length=100, null=True)),
                ('page_user_browser', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='log_progress_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Current Date Time')),
                ('python_app', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True)),
                ('function_message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['current_datetime'], name='progress_index1')],
            },
        ),
        migrations.CreateModel(
            name='log_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Current Date Time')),
                ('python_app', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True)),
                ('function_message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['current_datetime'], name='messages_index1')],
            },
        ),
        migrations.CreateModel(
            name='log_error_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Current Date Time')),
                ('python_app', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_level', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['current_datetime'], name='error_index1')],
            },
        ),
    ]
