# Generated by Django 4.2.10 on 2025-03-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rx_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=300, verbose_name='RX Event Name')),
            ],
        ),
        migrations.CreateModel(
            name='stands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=300, verbose_name='stand name')),
                ('s_number', models.CharField(max_length=300, verbose_name='stand number')),
                ('s_rx_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
        ),
        migrations.CreateModel(
            name='stand_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_x', models.IntegerField(verbose_name='stand x')),
                ('sl_y', models.IntegerField(verbose_name='stand y')),
                ('sl_x_length', models.IntegerField(verbose_name='stand x length')),
                ('sl_y_length', models.IntegerField(verbose_name='stand y length')),
                ('sl_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stands')),
            ],
        ),
    ]
