# Generated by Django 4.2.10 on 2025-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rx_event_stands_stand_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='s_stand_fill_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='s_stand_fill_color'),
        ),
        migrations.AddField(
            model_name='stands',
            name='s_stand_outline_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='s_stand_outline_color'),
        ),
        migrations.AddField(
            model_name='stands',
            name='s_text_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stand text color'),
        ),
        migrations.AlterField(
            model_name='stands',
            name='s_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='stand name'),
        ),
        migrations.AlterField(
            model_name='stands',
            name='s_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='stand number'),
        ),
    ]
