# Generated by Django 4.2.10 on 2025-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stands_s_stand_fill_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='s_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
