# Generated by Django 4.2.10 on 2025-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stands_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx_event',
            name='re_floor_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='RX Event Floor Length'),
        ),
        migrations.AddField(
            model_name='rx_event',
            name='re_floor_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='RX Event Floor Width'),
        ),
    ]
