# Generated by Django 4.2.10 on 2025-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rx_event_re_floor_length_rx_event_re_floor_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rx_event',
            name='re_floor_width',
        ),
        migrations.AddField(
            model_name='rx_event',
            name='re_floor_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='RX Event Floor Height'),
        ),
    ]
