# Generated by Django 4.2.10 on 2025-03-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_rx_event_re_floor_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_sales_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_Company_Name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Company Name')),
                ('est_Recipient_Country', models.CharField(blank=True, max_length=300, null=True, verbose_name='Recipient Country')),
                ('est_Customer_Type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Customer Type')),
                ('est_Opportunity_Type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Opportunity Type')),
                ('est_Opportunity_Owner', models.CharField(blank=True, max_length=300, null=True, verbose_name='Opportunity Owner')),
                ('est_Stand_Name_Length_Width', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Name Length Width')),
                ('est_Stand_Area', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Area')),
                ('est_Number_of_Corners', models.CharField(blank=True, max_length=300, null=True, verbose_name='Number of Corners')),
                ('est_Stand_Zone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Zone')),
                ('est_Floor_Plan_Sector', models.CharField(blank=True, max_length=300, null=True, verbose_name='Floor Plan Sector')),
                ('est_Sharer_Entitlements', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sharer Entitlements')),
                ('est_Sharer_Companies', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sharer Companies')),
                ('est_Last_Modified_Date', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified Date')),
                ('est_Total_Net_Amount', models.CharField(blank=True, max_length=300, null=True, verbose_name='Total Net Amount')),
                ('est_Order_Created_Date', models.DateTimeField(blank=True, null=True, verbose_name='Order Created Date')),
                ('est_Packages_Sold', models.CharField(blank=True, max_length=300, null=True, verbose_name='Packages Sold')),
                ('est_Product_Name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Product Name')),
                ('est_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
        ),
    ]
