# Generated by Django 4.2.10 on 2025-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_event_sales_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_sales_transactions',
            name='est_Stand_Name_Cleaned',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Name Cleaned'),
        ),
        migrations.AddField(
            model_name='event_sales_transactions',
            name='est_Stand_Name_Dim_Cleaned',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Name Cleaned'),
        ),
    ]
