# Generated by Django 4.2.10 on 2025-03-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_sales_transactions_est_stand_name_cleaned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_sales_transactions',
            old_name='est_stand',
            new_name='est_event',
        ),
    ]
