# Generated by Django 4.2.10 on 2025-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_est_stand_event_sales_transactions_est_event'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stands',
            index=models.Index(fields=['s_rx_event', 's_number'], name='stand_index1'),
        ),
        migrations.AddIndex(
            model_name='stands',
            index=models.Index(fields=['s_rx_event', 's_name'], name='stand_index2'),
        ),
    ]
