# Generated by Django 4.2.10 on 2025-03-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_stands_stand_index1_stands_stand_index2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx_event',
            name='re_event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RX Event End Date'),
        ),
        migrations.AddField(
            model_name='rx_event',
            name='re_event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RX Event Start Date'),
        ),
    ]
