# Generated by Django 4.2.10 on 2025-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rx_event_re_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='s_stand_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stand status'),
        ),
    ]
