# Generated by Django 4.2.10 on 2025-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_stands_s_stand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='s_stand_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stand price'),
        ),
    ]
