# Generated by Django 4.2.10 on 2025-03-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_stands_s_stand_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_fill_color',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_outline_color',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='s_text_color',
        ),
        migrations.CreateModel(
            name='event_stand_count_by_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escby_date', models.DateTimeField(blank=True, null=True, verbose_name='escby date')),
                ('escby_x_length', models.IntegerField(verbose_name='escby x length')),
                ('escby_y_length', models.IntegerField(verbose_name='escby y length')),
                ('escby_stand_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='escby stand status')),
                ('escby_stand_count', models.IntegerField(blank=True, null=True, verbose_name='escby Stand Count')),
                ('escby_rx_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
        ),
    ]
