# Generated by Django 4.2.10 on 2025-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_stands_s_stand_fill_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='s_stand_price_gradient',
            field=models.IntegerField(blank=True, null=True, verbose_name='stand price gradient'),
        ),
        migrations.AddField(
            model_name='stands',
            name='s_stand_price_per_sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='stand price per sq ft'),
        ),
        migrations.AddIndex(
            model_name='event_stand_count_by_date',
            index=models.Index(fields=['escby_rx_event', 'escby_date', 'escby_stand_status', 'escby_x_length', 'escby_y_length'], name='escby_index1'),
        ),
    ]
