# Generated by Django 4.2.10 on 2025-04-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_stands_s_stand_price_gradient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stand_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_analysis_number', models.IntegerField(verbose_name='analysis number')),
                ('sa_analysis_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='analysis title')),
                ('sa_analysis_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='analysis description')),
                ('sa_analysis_integer', models.IntegerField(blank=True, null=True, verbose_name='analysis integer')),
                ('sa_analysis_float', models.FloatField(blank=True, null=True, verbose_name='analysis float')),
                ('sa_analysis_string', models.CharField(blank=True, max_length=300, null=True, verbose_name='analysis string')),
                ('sa_analysis_datetime', models.DateTimeField(blank=True, null=True, verbose_name='analysis datetime')),
                ('sa_analysis_boolean', models.BooleanField(blank=True, null=True, verbose_name='analysis boolean')),
            ],
        ),
        migrations.AddIndex(
            model_name='stand_location',
            index=models.Index(fields=['sl_stand'], name='stand_location_index1'),
        ),
        migrations.AddField(
            model_name='stand_analysis',
            name='sa_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stands'),
        ),
        migrations.AddIndex(
            model_name='stand_analysis',
            index=models.Index(fields=['sa_stand', 'sa_analysis_number'], name='stand_analysis_index1'),
        ),
        migrations.AddIndex(
            model_name='stand_analysis',
            index=models.Index(fields=['sa_stand', 'sa_analysis_title'], name='stand_analysis_index2'),
        ),
    ]
