# Generated by Django 4.2.10 on 2025-04-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_stand_analysis_sa_analysis_boolean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rx_event_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=300, verbose_name='RX Event Group Name')),
            ],
        ),
        migrations.AddField(
            model_name='rx_event',
            name='re_event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event_group'),
        ),
    ]
