# Generated by Django 4.2.10 on 2025-04-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rx_event_group_rx_event_re_event_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing_rules_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prb_number', models.IntegerField(verbose_name='pricing rule base number')),
                ('prb_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='pricing rule base title')),
                ('prb_value', models.CharField(blank=True, max_length=300, null=True, verbose_name='pricing rule base value')),
                ('prb_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='pricing rule base type')),
                ('prb_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='pricing rule base start datetime')),
                ('prb_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='pricing rule base end datetime')),
                ('prb_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
            options={
                'indexes': [models.Index(fields=['prb_event', 'prb_number'], name='prb_index1'), models.Index(fields=['prb_event', 'prb_title'], name='prb_index2')],
            },
        ),
    ]
