# Generated by Django 4.2.10 on 2025-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_pricing_rules_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_rules_base',
            name='prb_run_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='pricing rule base run id'),
        ),
    ]
