# Generated by Django 4.2.10 on 2025-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_pricing_rules_base_prb_run_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricing_rules_base',
            name='prb_index1',
        ),
        migrations.RemoveIndex(
            model_name='pricing_rules_base',
            name='prb_index2',
        ),
        migrations.AddIndex(
            model_name='pricing_rules_base',
            index=models.Index(fields=['prb_event', 'prb_run_id', 'prb_number'], name='prb_index1'),
        ),
        migrations.AddIndex(
            model_name='pricing_rules_base',
            index=models.Index(fields=['prb_event', 'prb_run_id', 'prb_title'], name='prb_index2'),
        ),
    ]
