# Generated by Django 4.2.10 on 2025-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_pricing_rules_base_prb_index1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pricing_rules_base',
            new_name='pricing_rules',
        ),
    ]
