# Generated by Django 4.2.10 on 2025-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_pricing_rules_prb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_rules',
            name='prb_quantity',
        ),
    ]
