# Generated by Django 4.2.10 on 2025-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_pricing_rules_prb_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stand_analysis',
            name='stand_analysis_index1',
        ),
        migrations.RemoveIndex(
            model_name='stand_analysis',
            name='stand_analysis_index2',
        ),
        migrations.AddField(
            model_name='stand_analysis',
            name='sa_run_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='monte carlo run id'),
        ),
        migrations.AlterField(
            model_name='pricing_rules',
            name='prb_run_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto carlo run id'),
        ),
        migrations.AddIndex(
            model_name='stand_analysis',
            index=models.Index(fields=['sa_stand', 'sa_run_id', 'sa_analysis_number'], name='stand_analysis_index1'),
        ),
        migrations.AddIndex(
            model_name='stand_analysis',
            index=models.Index(fields=['sa_stand', 'sa_run_id', 'sa_analysis_title'], name='stand_analysis_index2'),
        ),
    ]
