# Generated by Django 4.2.10 on 2025-04-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_stand_analysis_stand_analysis_index1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stand_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_number', models.IntegerField(verbose_name='stand attribute number')),
                ('sa_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='stand attribute title')),
                ('sa_value', models.CharField(blank=True, max_length=300, null=True, verbose_name='stand attribute value')),
                ('sa_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='stand attribute type')),
                ('sa_datetime', models.DateTimeField(blank=True, null=True, verbose_name='stand attribute datetime')),
                ('sa_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stands')),
            ],
            options={
                'indexes': [models.Index(fields=['sa_stand', 'sa_number'], name='stand_attributes_index1'), models.Index(fields=['sa_stand', 'sa_title'], name='stand_attributes_index2')],
            },
        ),
    ]
