# Generated by Django 4.2.10 on 2025-04-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_stand_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_price',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_price_gradient',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_price_per_sq_ft',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='s_stand_status',
        ),
        migrations.DeleteModel(
            name='stand_location',
        ),
    ]
