# Generated by Django 4.2.10 on 2025-04-06 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_stands_s_stand_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stands_attribute_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sad_stand_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Name')),
                ('sad_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Title')),
                ('sad_value', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Value')),
                ('sad_data_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Data Type')),
                ('sad_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Stand Date Time')),
                ('sad_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
            options={
                'indexes': [models.Index(fields=['sad_event', 'sad_stand_name', 'sad_title'], name='stands_attribute_data_index1')],
            },
        ),
    ]
