# Generated by Django 4.2.10 on 2025-04-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_stands_attribute_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_sales_transactions_grouped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estg_Stand_Area', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Area')),
                ('estg_Number_of_Corners', models.CharField(blank=True, max_length=300, null=True, verbose_name='Number of Corners')),
                ('estg_Stand_Zone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Stand Zone')),
                ('estg_Floor_Plan_Sector', models.CharField(blank=True, max_length=300, null=True, verbose_name='Floor Plan Sector')),
                ('estg_Packages_Sold', models.CharField(blank=True, max_length=300, null=True, verbose_name='Packages Sold')),
                ('estg_count', models.IntegerField(blank=True, null=True, verbose_name='Count')),
                ('estg_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Min')),
                ('estg_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Max')),
                ('estg_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Avg')),
                ('estg_median', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Median')),
                ('estg_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rx_event')),
            ],
        ),
    ]
