# Generated by Django 4.2.10 on 2025-04-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_event_sales_transactions_grouped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_sales_transactions_grouped',
            name='estg_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Avg'),
        ),
        migrations.AlterField(
            model_name='event_sales_transactions_grouped',
            name='estg_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='event_sales_transactions_grouped',
            name='estg_median',
            field=models.FloatField(blank=True, null=True, verbose_name='Median'),
        ),
        migrations.AlterField(
            model_name='event_sales_transactions_grouped',
            name='estg_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Min'),
        ),
    ]
