# Generated by Django 4.2.10 on 2025-04-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_event_sales_transactions_grouped_estg_avg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_sales_by_run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esbr_run_id', models.IntegerField(blank=True, null=True, verbose_name='monte carlo run id')),
                ('esbr_sold_date', models.DateTimeField(blank=True, null=True, verbose_name='sold date')),
                ('esbr_revenue_amount', models.FloatField(blank=True, null=True, verbose_name='revenue amount')),
                ('esbr_total_revenue_to_date', models.FloatField(blank=True, null=True, verbose_name='total revenue to date')),
                ('esbr_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stands')),
            ],
            options={
                'indexes': [models.Index(fields=['esbr_run_id', 'esbr_sold_date', 'esbr_stand'], name='esbr_index1'), models.Index(fields=['esbr_sold_date', 'esbr_run_id', 'esbr_stand'], name='esbr_index2')],
            },
        ),
    ]
